name: "Topcoder Action Agent"
description: "Topcoder AI Agent supporting operations using LLMs."
branding:
  icon: "activity"
  color: "green"

env:
  AI_AGENT_MODEL: "qwen3:latest"
  AI_AGENT_TEMPERATURE: "0.5"
  AI_AGENT_NUM_CONTEXT: "4096"

jobs:
  ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Install ollama
        run: curl -fsSL https://ollama.com/install.sh | sh

      - name: Create & Configure LLM
        run: ./create-llm.sh

      - name: Check ollama version
        run: ollama -v && ollama ls

  # goose:
  #   needs: ollama
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Install Goose AI Agent
  #       run: |
  #         mkdir -p /home/runner/.local/bin
  #         curl -fsSL https://github.com/block/goose/releases/download/stable/download_cli.sh \
  #           | CONFIGURE=false INSTALL_PATH=/home/runner/.local/bin bash
  #         echo "/home/runner/.local/bin" >> $GITHUB_PATH

  #     - name: Configure Goose
  #       run: |
  #         mkdir -p ~/.config/goose
  #         cat <<EOF > ~/.config/goose/config.yaml
  #         GOOSE_PROVIDER: ollama
  #         GOOSE_MODEL: ${{ AI_AGENT_MODEL }}-tc-agentic-ai
  #         keyring: false
  #         EOF
  #     - name: Check Goose Version
  #       run: goose --version
